### ISSUE TITLE
Fail while running precast.py file

### ISSUE THREAD

**Issue by diane416** [peiyunh/ff#5]
Hi, I'm a newbie studying about using deep learning to predict future trajectory on cars.
I have been studying your paper, and I am now starting to run your code.
I made a dockerfile to run this code by using nuscenes' mini data, and I succeed on running "preprocess.py", 
but I failed while running "precast.py". 

I got this error, " keyerror : 'train on all sweeps' ", and I would like to get some advice on how to solve this error.
Also if possible, could you explain the order in which code should be executed?

It would be a great honor to run your code by your help.

(base) root@b1d627403c9b:/usr/src/app# python -W ignore precast.py 
Using /root/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/raycaster/build.ninja...
Building extension module raycaster...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=raycaster -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.6/site-packages/torch/include -isystem /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.6/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /usr/src/app/lib/raycast/raycaster.cu -o raycaster.cuda.o 
[2/2] c++ raycaster.o raycaster.cuda.o -shared -L/opt/conda/lib/python3.6/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o raycaster.so
Loading extension module raycaster...

Loading NuScenes tables for version v1.0-mini...
Loading nuScenes-lidarseg...
32 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
404 lidarseg,
Done loading in 0.375 seconds.

Reverse indexing ...
Done reverse indexing in 0.1 seconds.

Traceback (most recent call last):
  File "precast.py", line 29, in <module>
    dataset = nuScenesDataset(nusc, "train", dataset_kwargs)
  File "/usr/src/app/data.py", line 106, in __init__
    self.train_on_all_sweeps = kwargs["train_on_all_sweeps"]
KeyError: 'train_on_all_sweeps'

**Comment by Terence233** [comment]
I have the same issue
